### PR TITLE
Making sidebar scrollable

### PR DESCRIPTION
**Pull request by forresthopkinsa**
Duplicate of rlemon/se-chat-dark-theme-plus#56. For the sake of inclusivity.

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
I cannot reproduce this. It seems like chat itself makes stars that are no longer visible with display: none; to change the number of items in the list.

Is this still relevant? If so, in what case?

**Comment by forresthopkinsa** [comment]
Behold:

image

**Comment by MadaraUchiha** [comment]
Again, in that state, chat itself sets `display: none;` on all of the stars. I'm not convinced that adding a scrollbar is going to change that.

**Comment by forresthopkinsa** [comment]
Kablam

**Comment by MadaraUchiha** [comment]
Merged to the [`typescriptify`](https://github.com/MadaraUchiha/se-chat-dark-theme-plus/tree/typescriptify) branch, which, while a WIP, is the branch I'm currently deploying from.

**Pull request closed without merging**
